# Generated by Django 5.1.3 on 2024-12-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='x',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
    ]
